# Generated by Django 3.1.2 on 2021-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodesOfServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfService', models.CharField(max_length=50, null=True, verbose_name='كود الخدمة')),
                ('codeOfService', models.IntegerField(max_length=50, null=True, verbose_name='كود الخدمة')),
                ('kindOfService', models.IntegerField(choices=[('إتصالات وإنترنت', 'إتصالات وإنترنت'), ('مرافق عامة', 'مرافق عامة'), ('خدمات المرور', 'خدمات المرور'), ('معاملات مالية وبنوك', 'معاملات مالية وبنوك'), (' فورى باى', 'فورى باى'), ('خدمات التاجر', 'خدمات التاجر'), ('التبرعات', 'التبرعات'), ('إشتراكات وإعلانات', 'إشتراكات وإعلانات'), ('التعليم', 'التعليم'), ('التأمين', 'التأمين'), ('خدمات أخرى', 'خدمات أخرى'), ('الأكواد الخطأ', 'الأكواد الخطأ')], max_length=50, verbose_name='نوع الخدمة')),
            ],
        ),
    ]
