# Generated by Django 3.1.2 on 2021-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagerIssues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesofservices',
            name='codeOfService',
            field=models.IntegerField(null=True, verbose_name='كود الخدمة'),
        ),
    ]
