# Generated by Django 3.1.2 on 2020-11-01 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuerrySellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfMandoop', models.CharField(choices=[('a', 'وليد'), ('b', 'فايز'), ('c', 'حسن'), ('d', 'إبراهيم')], max_length=50, verbose_name='إسم المندوب')),
                ('area', models.CharField(max_length=50, verbose_name='المنطقة')),
                ('activityKind', models.CharField(choices=[('a', 'سنترال وخدمات محمول'), ('b', 'خدمات كمبيوتر')], max_length=20, verbose_name='نوع النشاط ')),
                ('shopName', models.CharField(max_length=50, verbose_name='إسم المحل ')),
                ('ownerName', models.CharField(max_length=50, verbose_name='إسم صاحب العمل ')),
                ('phoneNumber', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9+]', 'Only digit characters.')], verbose_name='رقم التليفون ')),
                ('address', models.TextField(max_length=100, verbose_name='العنوان بالتفصيل ')),
                ('machinesOfepay', models.CharField(choices=[('a', 'امان'), ('b', 'فورى'), ('c', 'بى'), ('d', 'مصارى'), ('e', 'ضامن'), ('f', 'سداد')], max_length=20, verbose_name='مكن الدفع الإلكترونى ')),
                ('tayer', models.CharField(choices=[('a', 'يوجد'), ('b', 'لا يوجد')], max_length=20, verbose_name='الطاير ')),
                ('amountOfTreat', models.CharField(choices=[('a', 'اقل من 10 الاف'), ('b', 'من 10 الاف ل 25000'), ('c', 'من 25 الف ل 50 الف'), ('d', 'اعلي من 50 الف')], max_length=20, verbose_name='حجم التعامل ')),
                ('kindOfMobile', models.CharField(choices=[('a', 'سامسونج'), ('b', 'هواوى'), ('c', 'أبل'), ('d', 'شاومى'), ('e', 'نوكيا'), ('f', 'انفنكس'), ('g', 'أوبو')], max_length=20, verbose_name='نوع اجهزه المحمول')),
                ('evaluate', models.CharField(choices=[('a', 'مهم'), ('b', 'مهم جدا'), ('c', 'متوسط'), ('d', 'غير مهم')], max_length=20, verbose_name='التقييم')),
                ('notes', models.TextField(max_length=100, verbose_name='الملاحظات')),
            ],
        ),
    ]
