# Generated by Django 3.1.2 on 2020-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querrysellers',
            name='intention',
            field=models.CharField(max_length=100, null=True, verbose_name='ما مدى قابليته للتعامل معنا'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='area',
            field=models.CharField(choices=[('a', 'نبروه'), ('b', 'بلقاس')], max_length=50, verbose_name='المنطقة'),
        ),
    ]
