# Generated by Django 3.1.2 on 2020-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='deviceName',
            field=models.CharField(max_length=50, null=True, verbose_name='نوع الجهاز'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='kind',
            field=models.CharField(max_length=50, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='raterName',
            field=models.CharField(max_length=50, null=True, verbose_name='إسم المقيم'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='activityKind',
            field=models.CharField(choices=[('سنترال وخدمات محمول', 'سنترال وخدمات محمول'), ('خدمات كمبيوتر', 'خدمات كمبيوتر'), ('عطارة', 'عطارة'), ('مكتبة', 'مكتبة'), ('بقالة', 'بقالة'), ('سوبر ماركت', 'سوبر ماركت'), ('other', 'أخر: ')], max_length=50, null=True, verbose_name='نوع النشاط '),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='amountOfTreat',
            field=models.CharField(choices=[('اقل من 10 الاف', 'اقل من 10 الاف'), ('من 10 الاف ل 25000', 'من 10 الاف ل 25000'), ('من 25 الف ل 50 الف', 'من 25 الف ل 50 الف'), ('اعلي من 50 الف', 'اعلي من 50 الف')], max_length=50, null=True, verbose_name='حجم التعامل '),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='area',
            field=models.CharField(choices=[('نبروه', 'نبروه'), ('بلقاس', 'بلقاس')], max_length=20, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='evaluate',
            field=models.CharField(choices=[('مهم', 'مهم'), ('مهم جدا', 'مهم جدا'), ('متوسط', 'متوسط'), ('غير مهم', 'غير مهم')], max_length=50, null=True, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='kindOfMobile',
            field=models.CharField(choices=[('سامسونج', 'سامسونج'), ('هواوى', 'هواوى'), ('أبل', 'أبل'), ('شاومى', 'شاومى'), ('نوكيا', 'نوكيا'), ('انفنكس', 'انفنكس'), ('أوبو', 'أوبو')], max_length=200, null=True, verbose_name='نوع اجهزه المحمول'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='machinesOfepay',
            field=models.CharField(choices=[('امان', 'امان'), ('فورى', 'فورى'), ('بى', 'بى'), ('مصارى', 'مصارى'), ('ضامن', 'ضامن'), ('سداد', 'سداد')], max_length=200, null=True, verbose_name='مكن الدفع الإلكترونى '),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='nameOfMandoop',
            field=models.CharField(choices=[('فايز', 'وليد'), ('فايز', 'فايز'), ('حسن', 'حسن'), ('إبراهيم', 'إبراهيم'), ('خط دكرنس', 'خط دكرنس')], max_length=100, verbose_name='إسم المندوب'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='notes',
            field=models.TextField(max_length=150, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='sim',
            field=models.CharField(choices=[('فودافون', ' فودافون'), ('إتصالات', 'إتصالات'), ('أورنج', 'أورنج')], max_length=150, null=True, verbose_name='الكارت'),
        ),
    ]
