# Generated by Django 3.1.2 on 2020-11-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0004_auto_20201102_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='querrysellers',
            name='date',
            field=models.DateField(null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='querrysellers',
            name='time',
            field=models.TimeField(null=True, verbose_name='الوقت'),
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20, null=True, verbose_name='نوع الجهاز')),
                ('rate', models.IntegerField(null=True, verbose_name='المقيمين')),
                ('time', models.DateField(null=True, verbose_name='الوقت')),
                ('rater', models.ManyToManyField(null=True, to='querriesTraders.QuerrySellers')),
            ],
        ),
    ]
