# Generated by Django 3.1.2 on 2020-11-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0005_auto_20201103_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='rater',
        ),
        migrations.AddField(
            model_name='devices',
            name='date',
            field=models.DateField(null=True, verbose_name='التاريخ'),
        ),
        migrations.AddField(
            model_name='devices',
            name='raterName',
            field=models.CharField(max_length=20, null=True, verbose_name='إسم المقيم'),
        ),
        migrations.AddField(
            model_name='devices',
            name='rater_id',
            field=models.IntegerField(null=True, verbose_name='المقيم'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='rate',
            field=models.FloatField(null=True, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='time',
            field=models.TimeField(null=True, verbose_name='الوقت'),
        ),
    ]
