# Generated by Django 3.1.2 on 2020-11-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0006_auto_20201108_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='rater_id',
            new_name='raterid',
        ),
    ]
