# Generated by Django 3.1.2 on 2020-11-08 01:10

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0007_auto_20201108_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='querrysellers',
            name='addressmap',
            field=django_google_maps.fields.AddressField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='querrysellers',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
    ]
