# Generated by Django 3.1.2 on 2020-11-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0008_auto_20201108_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='querrysellers',
            name='sim',
            field=models.CharField(choices=[('فودافون', ' فودافون'), ('إتصالات', 'إتصالات'), ('أورنج', 'أورنج')], max_length=20, null=True, verbose_name='الكارت'),
        ),
        migrations.AlterField(
            model_name='querrysellers',
            name='activityKind',
            field=models.CharField(choices=[('سنترال وخدمات محمول', 'سنترال وخدمات محمول'), ('خدمات كمبيوتر', 'خدمات كمبيوتر'), ('عطارة', 'عطارة'), ('مكتبة', 'مكتبة'), ('بقالة', 'بقالة'), ('other', 'أخر: ')], max_length=20, null=True, verbose_name='نوع النشاط '),
        ),
    ]
