# Generated by Django 3.1.2 on 2020-11-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0009_auto_20201108_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querrysellers',
            name='activityKind',
            field=models.CharField(choices=[('سنترال وخدمات محمول', 'سنترال وخدمات محمول'), ('خدمات كمبيوتر', 'خدمات كمبيوتر'), ('عطارة', 'عطارة'), ('مكتبة', 'مكتبة'), ('بقالة', 'بقالة'), ('سوبر ماركت', 'سوبر ماركت'), ('other', 'أخر: ')], max_length=20, null=True, verbose_name='نوع النشاط '),
        ),
    ]
