# Generated by Django 3.1.2 on 2020-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querriesTraders', '0011_auto_20201108_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='kind',
            field=models.CharField(max_length=20, null=True, verbose_name='النوع'),
        ),
    ]
